dofile('Scripts/Database/Weapons/warheads.lua')

tail_solid  = { 1, 1, 1, 1 };
tail_liquid = { 0.9, 0.9, 0.9, 0.05 };

--================== JF-17 ==================================--
dofile(current_mod_path .. '/JF-39/JF17_Loadouts/tools.lua')
dofile(current_mod_path .. '/JF-39/JF17_Loadouts/sensors.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/bomb_type200.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/bomb_misc.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/jsow_ls6.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/jsow_gb6.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/rkt_brm1.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/rkt_misc.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/mils_c701.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/mils_c802ak.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/mils_cm802akg.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/mils_ld10.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/mils_pl5.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/mils_sd10.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/mils_pl8.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/mils_akd.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/mils_yj12.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/mils_kd63.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/mils_kd20.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/pod_dlink.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/pod_spj.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/pod_wmd7.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/pod_misc.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/fuel_tank.lua')
--dofile(current_mod_path .. '/JF-39/JF17_Loadouts/jdam_ls6.lua')
--================== JF-39 ==================================--
dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_bomb_misc.lua')
dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_c802ak.lua')
dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_cm802akg.lua')
dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_pods.lua')
dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_fuel.lua')
dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_iraam.lua')
dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_bvraam.lua')
dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_sdb.lua')
dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_brimstone.lua')
dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_m70b.lua')
dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_mar-1.lua')
--dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_spear_3.lua')
--dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_gbu-32.lua')
--dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_gbu-38.lua')
--dofile(current_mod_path .. '/JF-39/JF39_Loadouts/jf39_gbu-49.lua')
----------------------------------------------------------------------------------------
--                    File by whisky.actual@gmail.com - v.1.1.1                       --
----------------------------------------------------------------------------------------
